version: 2.1

jobs:
  init-ci:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
  build-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed minhtue37/udagram-api-feed:v0
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user minhtue37/udagram-api-user:v0
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend minhtue37/udagram-frontend:v0
            docker build -t udagram-reverseproxy:v1 ./udagram-reverseproxy
            docker tag udagram-reverseproxy:v1 minhtue37/udagram-reverseproxy:v1
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push minhtue37/udagram-api-feed:v0
            docker push minhtue37/udagram-api-user:v0
            docker push minhtue37/udagram-frontend:v0
            docker push minhtue37/udagram-reverseproxy:v1
workflows:
  default:
    jobs:
      - init-ci
      - build-image:
          requires: [init-ci]